### PR TITLE
Update "golden.panicking_test" to match Golang-1.5 output (Closes: #28).

### PR DESCRIPTION
**Pull request by onlyjob**

### CODE REVIEW

**Comment by jacobsa** [comment]
Thanks, but you probably want to chase Go 1.6 now, right?

**Comment by onlyjob** [comment]
There were no Golang 1.6 in Debian "unstable" when I submitted this pull request...
Frankly I don't really "want" to chase it -- I'm just doing what's necessary to fix FTBFS affecting the whole hierarchy of depending packages...

Maybe you could do something (like disabling this test) to avoid updates of golden.paniking_test for every new version of Golang?

**Comment by jacobsa** [comment]
Are you sure this package (and its dependents) are even need in Debian anymore? I believe they're only there because of an attempt to adding GoogleCloudPlatform/gcsfuse that never actually materialized. Please feel free to get rid of them if that is easier.

**Comment by onlyjob** [comment]
> Are you sure this package (and its dependents) are even needed in Debian?

Positive. Otherwise I wouldn't be bothering you, wouldn't I? Anyway this is not the point...

Any ideas how you could fix that test permanently, to avoid various output from differebt versions of Golang?

**Comment by jacobsa** [comment]
Please explain for my curiosity how you're positive it's needed? What is it used by that anybody actually cares about? (This is news to me.)

I will take a look at making the test less picky, or at least setting it up to support various Go version and OS combinations.

**Comment by onlyjob** [comment]
> Please explain for my curiosity how you're positive it's needed?

_Ogletest_ is used (indirectly) by [grafana](https://tracker.debian.org/pkg/grafana), [grafana-zabbix](https://tracker.debian.org/pkg/grafana-zabbix) through _go-macaron_ packages; by [aws-sdk-go](https://tracker.debian.org/pkg/golang-github-aws-aws-sdk-go) (which is a dependency of Kubernetes); by _smartystreets-goconvey_ and possibly others... 

> What is it used by that anybody actually cares about?

Why do you imply that we don't care about our packages? That's not nice... :(

> I will take a look at making the test less picky, or at least setting it up to support various Go version and OS combinations.

Thank you, that would be great as test broke again with Golang 1.6...

**Comment by jacobsa** [comment]
Sorry, I was implying only that the package for GoogleCloudPlatform/gcsfuse (which I wrote) was uncared for, not any others. I didn't realize there were other users.

Will take a look soon.

**Comment by onlyjob** [comment]
Thanks. You mean [golang-github-jacobsa-bazilfuse](https://tracker.debian.org/pkg/golang-github-jacobsa-bazilfuse)? I don't see any problems like unanswered bugs etc... Though I'm not sure if I identified the the right package for `GoogleCloudPlatform/gcsfuse`...

**Comment by jacobsa** [comment]
Okay, I believe the above commit will put your tests into a happy state. Sorry for the delay.

**Comment by onlyjob** [comment]
Brilliant, bfb9790 works perfectly for both Golang 1.5. and 1.6.
Thank you very much. :)

**Pull request closed without merging**
